version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - sed -i "s/BUILD_PLACEHOLDER_SUFFIX/$SUFFIX/g" app/build.gradle
      - sed -i "s/BUILD_PLACEHOLDER_API_KEY/$APIKEY/g" app/src/demo/AndroidManifest.xml
  build:
    commands:
      - echo Build started on `date`
      - gradle clean assembleRelease 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - app/build/outputs/apk/demo/release/hover-tester-demo-release.apk
